name: Java CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: My first action
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: create settings.xml
      run: echo "<settings><servers><server><id>github</id><password>${GH_TOKEN}</password></server></servers></settings>" > settings.xml
    - name: Build with Maven
      run: mvn -B site -Pdeploy --file pom.xml -s settings.xml

      
