name: Java CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B site --file pom.xml
    - name: Deploy with Maven
      uses: "Cecilapp/GitHub-Pages-deploy@master"
      env:
       BUILD_DIR: "target/site/"
       TARGET_BRANCH: "gh-pages"   
       CNAME: "jchateau.org"        # in case of custom domain
       EMAIL: "publish@jchateau.org" # must be a verifed email
       JEKYLL_SITE: "NO"        # only in case of a Jekyll site
      
