name: mvn -B site -Pdeploy

on:
  create:
    tags:
      - v*      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v4.1.17

    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B site --file pom.xml

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/site # The folder the action should deploy.
      
